### ISSUE TITLE
API thoughts

### ISSUE THREAD

**Issue by hasufell** [RaphaelJ/friday#13]
I'm fairly new to haskell (~1 year) and the only bigger lib I've used for some time now is Diagrams.

Now I was looking into basic image processing and wanted to do stuff like image noise reduction by calculating the average of a number of images.

The functions ```fromFunction``` and ```map``` are fairly basic, so I tried a few hacks like:
```haskell
map2 :: (I.Image src1, I.Image src2, I.FromFunction res)
     => Size
     -> (I.ImagePixel src1 -> I.ImagePixel src2 -> I.FromFunctionPixel res)
     -> src1
     -> src2
     -> res
map2 s f img1 img2 =
  I.fromFunction s $ \pix ->
       f (img1 `I.index` pix) (img2 `I.index` pix)


foldImg :: (I.Image i, I.FromFunction i)
        => Size
        -> (I.ImagePixel i -> I.ImagePixel i -> I.FromFunctionPixel i)
        -> [i]
        -> i
foldImg s f = foldl1 (map2 s f)
```

Maybe I missed something, but I think this library could benefit from a more powerful interface.

**Comment by hasufell** [comment]
no response, maintainer is probably not interested in input

**Comment by TomMD** [comment]
@hasufell The original maintainer is busy with a start-up and I've been less involved than I had intended since my use of the library has gone down a good bit.  Don't assume a lack of interest from a lack of response!  I agree there is a wealth of combinators that this library could use, but fleshing out a full set of these that work well together is certainly a non-trivial task.  It's even harder, but critical, to do so and remain true to the style and terminology used in the rest of the Haskell eco-system - for example, your `map2` should probably be called `zip`.

**Comment by hasufell** [comment]
> Don't assume a lack of interest from a lack of response!

I think it's fairly sensible to assume it. That's how communication works.

And as it is now, I have no interest anymore and I don't really use this library. Thanks for your response though.
